version: '3.9'

services:
  redis-server:
    container_name: ${REDIS_TCP_HOST}
    image: docker.io/library/redis:${REDIS_TAG}
    volumes:
      - ./test/eredis_SUITE_data/config/redis-tcp.conf:/usr/local/etc/redis/redis.conf
      - ./test/eredis_SUITE_data/config/users.acl:/usr/local/etc/redis/users.acl
    ports:
      - "${REDIS_TCP_PORT}:${REDIS_TCP_PORT}"
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-server-tls:
    container_name: ${REDIS_TLS_HOST}
    image: docker.io/library/redis:${REDIS_TAG}
    volumes:
      - ./test/eredis_SUITE_data/certs/redis.crt:/etc/certs/redis.crt
      - ./test/eredis_SUITE_data/certs/redis.key:/etc/certs/redis.key
      - ./test/eredis_SUITE_data/certs/ca.crt:/etc/certs/ca.crt
      - ./test/eredis_SUITE_data/config/redis-tls.conf:/usr/local/etc/redis/redis.conf
      - ./test/eredis_SUITE_data/config/users.acl:/usr/local/etc/redis/users.acl
    ports:
      - "${REDIS_TLS_PORT}:${REDIS_TLS_PORT}"
    command: redis-server /usr/local/etc/redis/redis.conf
